spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongodb-test
      username: rootuser
      password: rootpassword
      authentication-database: admin
  profiles:
    active: dev
